@url = http://localhost:3000
### cats
GET {{url}}/cats?id=1
### cat
GET {{url}}/cats/5237
### cat
GET {{url}}/cats/5238
### cat
GET {{url}}/cats/52388882?age=26&foo=bar
### add
POST {{url}}/cats
Content-Type: application/json

{
    "id": 52788,
    "age": 19,
    "foo": "bar"
}
### update
PUT {{url}}/cats/12138
Content-Type: application/json

{
    "id": 52788,
    "age": 37
}
### delete
DELETE {{url}}/cats/5238
### docs
GET {{url}}/cats/docs