@url = http://localhost:5002

### cats
GET {{url}}/cats
###
GET {{url}}/cats/observable
###
GET {{url}}/cats?id=y2z8wz
###
GET {{url}}/cats?id=y2z8wz&foo=bar
###
GET {{url}}/cats/showparams?id=y2z8wz&foo=bar


### 301
GET {{url}}/cats/docs


### fastify
GET {{url}}/cats/fastify
### 
GET {{url}}/cats/fastify2


### cat
### use id from list
GET {{url}}/cats/XXXXX
### special
GET {{url}}/cats/y2z8wz
### 404
GET {{url}}/cats/404cat
### 
GET {{url}}/cats/unhandlecat/throw
### 
GET {{url}}/cats/unhandlecat/reject

### cats
GET {{url}}/cats?_dev_=1
### 
GET {{url}}/cats/uid/80
### 
GET {{url}}/cats/uid/notnumb

### add
POST {{url}}/cats
Content-Type: application/json

{
    "id": 52788,
    "age": 19,
    "foo": "bar"
}
### 
POST {{url}}/cats
Content-Type: application/json

{
    "id": 52788,
    "age": 19,
    "foo": "bar"
}
### 
POST {{url}}/cats/validation1
Content-Type: application/json

{
    "name": "fooo",
    "age": 19,
    "breed": "LIHUA",
    "foo": "bar"
}

### 
POST {{url}}/cats/validation1
Content-Type: application/json

{
    "age": 19,
    "foo": "bar"
}
### 
POST {{url}}/cats/validation2
Content-Type: application/json

{
    "name": "fooo",
    "age": 19,
    "breed": "LIHUA",
    "foo": "bar"
}

### 
POST {{url}}/cats/validation2
Content-Type: application/json

{
    "age": 19,
    "foo": "bar"
}



### update
PUT {{url}}/cats/12138
Content-Type: application/json

{
    "id": 52788,
    "age": 37
}

### delete
DELETE {{url}}/cats/5238


### all
GET {{url}}/cats/fooo/method
### 
POST {{url}}/cats/fooo/method

###
GET {{url}}/cats/foobf